### ISSUE TITLE
クロスサイトリクエストフォージェリ(CSRF)対策

### ISSUE THREAD

**Issue by e1211033** [e1211033/lamp_practice#5]
POST投稿時に「トークン」と呼ばれるランダムな文字列を使用する様に修正。
手順は以下を参考にすること。
1. トークンの生成・埋め込み
2. トークンの照合
3. トークンの破棄・再生成

**Comment by e1211033** [comment]
@primestyleus  
本課題(課題1-3)に関して以下の変更を行う予定です。
確認の程よろしくお願い致します。


[修正内容]
①トークンの生成用関数、照合用関数の追加
　トークンを生成する関数(get_csrf_token())およびトークンを照合する関数(is_valid_csrf_token($token))を追加
　(変更対象ファイル)
　・functions.php

②トークンの生成・埋め込み
　POST投稿を行う各フォームに対してトークンの埋め込み(<input type="hidden" name="token" value="<?php print(get_csrf_token()); ?>">)を追加
　(変更対象ファイル)
　・admin_view.php
　・cart_view.php
　・finish_view.php
　・index_view.php
　・login_view.php
　・signup_view.php

③トークンの照合・削除
　POST投稿の受け取り操作部分に対してトークンの照合および削除を追加
　(変更対象ファイル)
　・admin_change_status.php
　・admin_change_stock.php
　・admin_delete_item.php
　・admin_insert_item.php
　・cart_change_amount.php
　・cart_delete_cart.php
　・index_add_cart.php
　・login_process.php
　・signup_process.php

**Comment by primestyleus** [comment]
@e1211033 
概ね問題ないので実装進めてください。トークン生成はコントローラで行い、埋め込みだけをviewで行うとよりきれいにまとまります

**Comment by e1211033** [comment]
@primestyleus 
コメントありがとうございます！
トークン生成は以下の通りコントローラでするように致します。
よろしくお願い致します。


-----
[修正内容]
①トークンの生成用関数、照合用関数の追加
　トークンを生成する関数(get_csrf_token())およびトークンを照合する関数(is_valid_csrf_token($token))を追加
　(変更対象ファイル)
　・functions.php

②トークンの生成
　各コントローラにトークンの生成($token = get_csrf_token())を追加
　(変更対象ファイル)
　・admin.php
　・cart.php
　・finish.php
　・index.php
　・login.php
　・logout.php
　・signup.php


③トークンの埋め込み
　POST投稿を行う各フォームに対してトークンの埋め込み(<input type="hidden" name="token" value="<?php print ($token);>">)を追加
　(変更対象ファイル)
　・admin_view.php
　・cart_view.php
　・finish_view.php
　・index_view.php
　・login_view.php
　・signup_view.php

④トークンの照合・再生成
　POST投稿の受け取り操作部分に対してトークンの照合および再生成を追加
　(変更対象ファイル)
　・admin_change_status.php
　・admin_change_stock.php
　・admin_delete_item.php
　・admin_insert_item.php
　・cart_change_amount.php
　・cart_delete_cart.php
　・index_add_cart.php
　・login_process.php
　・signup_process.php

**Comment by e1211033** [comment]
@primestyleus 
いつもお世話になっております！

本課題のデバッグについて、以前のレッスンでフォームを用いずにPOST投稿ができるテストサイトがあると伺った気がするのですが、「csrf テストサイト」等で検索をしても使えそうなテストサイトを見つけられませんでした。

そこでお手数をお掛け致しますが、もしテストサイトがあるならばサイト名を教えて頂いてもよろしいでしょうか？
またその様なサイトが無い場合、フォームを用いずにPOST投稿させるにはどの様にすれば良いかご教示頂けますでしょうか？
(もし文面での対応が難しい場合はレッスンを予約しようと思っております。)

以上、回答の程よろしくお願い致します！

**Comment by primestyleus** [comment]
@e1211033 

おつかれさまです。

> フォームを用いずにPOST投稿ができる

postmanというツールがあります。
https://www.postman.com/downloads/

よろしければ使ってみてください。
